import { css } from '@emotion/react';

export const buttonCss = css`
  -webkit-box-align: center;
  align-items: center;
  -webkit-box-pack: center;
  justify-content: center;
  min-height: 25px;
  display: block;
  overflow: hidden;
  position: absolute;
  top: 24px;
  right: 24px;
  width: 24px;
  height: 24px;
  min-width: initial;
  background: url(//img.29cm.co.kr/next29cm/order/icon-remove.png) 0px 0px / 24px 24px no-repeat;
  line-height: 100em;
  border: 0;
  cursor: pointer;
  outline: none;
`;
export const tableWrap = css`
  position: relative;
  box-sizing: border-box;
`;
export const table = css`
  position: relative;
  display: table;
  width: 100%;
  table-layout: fixed;
  box-sizing: border-box;
`;
export const couponCell = css`
  position: absolute;
  padding: 0px 10px;
  display: flex;
  flex-wrap: wrap;
  place-content: center;
  -webkit-box-pack: center;
  top: 1px;
  right: 1px;
  bottom: 0px;
  width: 15%;
  z-index: 5;
  border-left: 1px solid rgb(228, 228, 228);
  background: rgb(255, 255, 255);
  font-size: 15px;
  font-weight: 600;
  color: rgb(0, 0, 0);
`;
export const tableCell = css`
  display: table-cell;
  padding: 30px 0px;
  border-top: 1px solid rgb(228, 228, 228);
  font-size: 18px;
  line-height: 24px;
  color: rgb(0, 0, 0);
  text-align: center;
  vertical-align: middle;
`;

export const buttonTableCell = css`
  display: table-cell;
  padding: 30px 0px;
  font-size: 18px;
  line-height: 24px;
  color: rgb(0, 0, 0);
  text-align: center;
  vertical-align: middle;
  width: 200px;
  border-style: solid;
  border-color: rgb(228, 228, 228);
  border-image: initial;
  border-width: 1px 1px 0px;
  box-sizing: border-box;
`;
export const productDetail = css`
  display: table-cell;
  border-top: 1px solid rgb(228, 228, 228);
  font-size: 18px;
  line-height: 24px;
  color: rgb(0, 0, 0);
  vertical-align: middle;
  position: relative;
  padding: 27px 60px 30px 0px;
  text-align: left;
  box-sizing: border-box;
`;
export const rightCountButton = css`
  isplay: flex;
  -webkit-box-align: center;
  align-items: center;
  -webkit-box-pack: center;
  justify-content: center;
  min-height: 25px;
  width: 36px;
  height: 36px;
  min-width: initial;
  border-width: 1px 1px 1px 0px;
  border-top-style: solid;
  border-right-style: solid;
  border-bottom-style: solid;
  border-top-color: rgb(228, 228, 228);
  border-right-color: rgb(228, 228, 228);
  border-bottom-color: rgb(228, 228, 228);
  border-image: initial;
  border-radius: 0px;
  background: rgb(255, 255, 255);
  font-size: 20px;
  font-weight: 400;
  color: rgb(160, 160, 160);
  border-left-style: initial;
  border-left-color: initial;
  box-sizing: border-box;
  cursor: pointer;
  outline: none;
  box-sizing: border-box;
`;
export const middelCountButton = css`
  display: block;
  color: rgb(26, 26, 26);
  outline: none;
  margin: 0px;
  padding: 0px;
  width: 37px;
  height: 36px;
  border: 1px solid rgb(228, 228, 228);
  font-size: 14px;
  font-weight: 500;
  text-align: center;
  writing-mode: horizontal-tb !important;
  box-sizing: border-box;
`;
export const leftCountButton = css`
  box-sizing: border-box;
  display: flex;
  -webkit-box-align: center;
  align-items: center;
  -webkit-box-pack: center;
  justify-content: center;
  min-height: 25px;
  width: 36px;
  height: 36px;
  min-width: initial;
  border-width: 1px 0px 1px 1px;
  border-top-style: solid;
  border-bottom-style: solid;
  border-left-style: solid;
  border-top-color: rgb(228, 228, 228);
  border-bottom-color: rgb(228, 228, 228);
  border-left-color: rgb(228, 228, 228);
  border-image: initial;
  border-radius: 0px;
  background: rgb(255, 255, 255);
  font-size: 20px;
  font-weight: 400;
  color: rgb(160, 160, 160);
  border-right-style: initial;
  border-right-color: initial;
  cursor: pointer;
  outline: none;
`;
export const buttonWrap = css`display: flex;',ont-size: 18px;
line-height: 24px;
color: rgb(0, 0, 0);
text-align: center;`;
